### ISSUE TITLE
Parse an existing git repository with CLI

### ISSUE THREAD

**Issue by albfan** [nicoespeon/gitgraph.js#117]
I want to use gitgraph.js in a custom command `git graph` 

https://github.com/albfan/git-graph

Is there any example parsing whole repository and printing it with gitgraph.js?

**Comment by nicoespeon** [comment]
Hi @albfan,

It sounds a lot like #38, but isn't implemented yet.

**Comment by albfan** [comment]
Yes, I know, just asking if you have any link avaliable.

Then there's only two task to do:

1. parse input format: Totally related with #38 I will start with github format, but would be better to define one for gitgraph, so people can implement a conversor from X to gitgraph.js format.
2. play around with gitgraph till satisfied http://jsfiddle.net/fracz/guan1oz1/374/

I will keep you informed from my progress here and in #38

**Comment by nicoespeon** [comment]
That'd be awesome 👌 

Please tell if you have any trouble doing so.

**Comment by albfan** [comment]
Of course. This will depend on #118 first, right? I will finish that first and then provide a general json walker and an implementation for github format.

**Comment by nicoespeon** [comment]
Sure.

That's good as it will improve the internal design and representations. Also, I guess it will point out issues with real-world scenarios if we can parse an actual graph.

**Comment by nicoespeon** [comment]
Worth a check: https://github.com/fabien0102/git2json

**Comment by nicoespeon** [comment]
For the record: this is waiting for #118, which is waiting for #38 😄

**Comment by nicoespeon** [comment]
This will be solved with #187. More information when we'll release it 👌

**Comment by nicoespeon** [comment]
We released `@gitgraph/react` which is a React rendering library for GitGraph.js. 

It exposes an `import()` method that allows you to generate a graph from a JSON output. See https://github.com/nicoespeon/gitgraph.js/issues/38#issuecomment-462098910 for details.

The JSON output can be generated from an existing repository with [git2json](https://github.com/fabien0102/git2json). For the moment, we won't include the CLI tool inside `@gitgraph` packages, but this might change. Any way, we'll document usage soon. 

I suggest you use git2json CLI on your git repository, then import the generated JSON into gitgraph through the `import()` function. If you find any bug (the feature is still a bit experimental), don't hesitate to open issues.

---

So, this is technically _not_ resolved for the `gitgraph.js` package… But we released `@gitgraph/react` in v1.0.0-0 and this issue was fixed here.

We won't maintain the `gitgraph.js` package. There will be a `@gitgraph/js` package soon to replace it. 

We still accept PRs if someone really needs it, but I'd suggest moving to the aforementioned packages. Thanks 🙏
