### ISSUE TITLE
preview changes

### ISSUE THREAD

**Issue by MetaiR** [nicoespeon/gitgraph.js#136]
did you see GitKeraken?
it has a WIP (it shows the changes which not committed)
you can see it as WIP: LocalTests (it's shown by dashes) in image:
![image](https://cloud.githubusercontent.com/assets/7807264/21653847/67349b40-d2c8-11e6-87e2-62022fc97daa.png)

I looked for it but I didn't find anything.
I think it's good if make this feature.
thanks

**Comment by nicoespeon** [comment]
Hi @MetaiR and thanks for the suggestion!

I'm wondering about the use case though. I see gitgraph.js much more like something that allows you to represent a git workflow on a webpage without having to draw it by hand, in a picture − this was our original use case, actually 😆 

The ambition I currently have is to make it able to dynamically create the graph from some input, so you'd be able to draw the graph of an existing project (see #38 and #117 for that).

In all of these use cases, there is no actual "WIP". You're only dealing with commits, changes actually committed to the repo. The library is here to display exactly that.

Git Kraken is great − I personally use [GitUp](http://gitup.co/) though, as I'm using a Mac. It's a fantastic Git GUI tool that helps you work with git easily. Displaying current changes that are staged or not, but not committed yet, is required since you need to commit with the tool. 

I feel like this is different. I don't think it's a feature for the lib.
But I'd like to hear your feedback / any use case example you might encounter that'd justify it 😃

**Comment by MetaiR** [comment]
@nicoespeon 
first of all thanks for your answer and attention.
this idea has a quite long story.
I'm working on Linux (ubuntu) and here we have just GitKraken that support all of the git feature and also easy and fast enough for working with git. it has WIP, cover conflicts and solves them with asking you which one correct and you can pick up one just by clicking on a checkbox and other good feature.
but there is a matter. GitKeraken is free for non-commercial use. this sentence destroyed me... anyway I decided to write a git GUI by myself which use python for its core (especially for using multithreading) and use the htmlPy module to build its GUI by HTML - CSS and javascript.
so one feature I thought, was to cover WIP.
and because I needed one javascript library to draw so I found you and I suggest this matter for this reason.

**Comment by nicoespeon** [comment]
I get your needs indeed =)

However that's very specific to the usage of a git GUI. But I guess what you need is the drew graph, and you handle the files changes by yourself. If so, a workaround would simply be to draw a "WIP-commit" to represent the WIP, like so:

```javascript
var gitGraph = new GitGraph({template: "metro", orientation: 'vertical-reverse'});

// Let's pretend the graph is constructed from git history
var master = gitGraph.branch("master").commit().commit();
var dev = gitGraph.branch("dev").commit().commit();
var feat1 = dev.branch("feature1").commit();
var feat2 = dev.branch("feature2").commit();
feat1.merge(dev);
master.commit();
dev.commit();
feat2.merge(dev);

// WIP-like "commit"
gitGraph.commit({
  dotStrokeWidth: 10,
  dotColor: "white",
  messageDisplay: false
})
```

This would produce something like:

<img width="1111" alt="wip-style-commit" src="https://cloud.githubusercontent.com/assets/1094774/21760263/f94a743e-d64a-11e6-93c8-684ab6db8b13.png">

Would that meet you needs?

**Comment by nicoespeon** [comment]
Unfortunately not, AFAIK.

I created #139 for that. I'm closing this issue if you have no further question − if so, feel free to ask / open an issue :wink:
