### ISSUE TITLE
Search facility

### ISSUE THREAD

**Issue by jcgonzales** [nicoespeon/gitgraph.js#141]
Hi, this is rather a request than an issue...

Is there a way to be able to search a branch, a tag via the navigator search facility (CTRL-F) ?

Thanks

JC

**Comment by nicoespeon** [comment]
Hi!

I don't think so since text is part of the canvas, hence it is not accessible.
To do so, I guess we should render part of the graph in plain HTML, which is not something easily feasible with current implementation.

If you do find a solution − or get an idea on how to do that, please share 😃 
Until then, I'm closing the issue with a "wontfix" because I don't have one.
