### ISSUE TITLE
Mode: Branch pointers only

### ISSUE THREAD

**Issue by JKrag** [nicoespeon/gitgraph.js#142]
It would be lovely if there was a mode "between" compact and standard. I would like something that just adds branch labels to the commit currently representing a branch.

Something along the lines of the following picture: 
![image](https://cloud.githubusercontent.com/assets/1712950/22108196/2b6303dc-de52-11e6-9b5e-72a44f46096b.png)
(generously borrowed from https://www.atlassian.com/git/tutorials/using-branches).

**Comment by JKrag** [comment]
I played around and noticed that there is a showLabel feature. As I am not used to JS, It took me some time even to work out how to set this property without having to write a whole template myself.
When I finally got it working, I found out that it didn't do what I hoped anyway :-)

I have now spent the evening reading and hacking around in the code and learnt a lot of JS along the way too. I did manage to put together a crude proof of concept: http://jsfiddle.net/fqpfgt9c/

If anyone wants to see exactly what I changed, the diff can be seen here: https://github.com/JKrag/gitgraph.js/commit/9b85562d731384c40d3f7a3938ef5dfa8354db42 

There is still a long way to go to figure out the spacing and stuff, but my hope is that someone more experienced in the codebase and JS can step in and build on this idea. 

I am really hoping to also get support for multiple branch labels at the same commit, and an optional HEAD label that shows the current checkout, but those are topics for other/future feature requests.

I.e. The end goal is that I want to be able to produce gitgraph.js graphs that are functionally equivalent to the following minimal example:
<img width="198" alt="cursor_and_explain_git_with_d3" src="https://cloud.githubusercontent.com/assets/1712950/22131531/5bb08002-deb4-11e6-834a-cc577378c8fa.png">
(Generated at [Explain git with d3](http://onlywei.github.io/explain-git-with-d3/#zen) using the commands:
```
git branch foo
git branch bar
git commit
git checkout bar
```

As stated, I do consider these separate features:
 -  This issue: branch labels/pointers at branch head
 - Multiple labels at same commit
 - HEAD label at current checked out branch 

I plan to create separate issues for the last two, but thought the overall idea was worth mentioning here as it may influence on implementation choices.

I hope this all makes a bit of sense and doesn't conflict with the current path of the project.

**Comment by nicoespeon** [comment]
Hi @JKrag,

Thanks for this detailed issue with many suggestions and digging.

Concerning the "display branch tags in compact mode" part, there is no obvious / documented way to do that indeed.
However, you were close. What you can do is create your own template that display branch labels. Extending the `"metro"` template, you would do something like:

```javascript
var metroWithBranchLabels = new GitGraph.Template({
  colors: ["#979797", "#008fb5", "#f1c109"],
  branch: {
    lineWidth: 10,
    spacingX: 50,
    labelRotation: 0,
    showLabel: true
  },
  commit: {
    spacingY: -80,
    dot: {
      size: 14
    },
    message: {
      font: "normal 14pt Arial"
    }
  }
});

var gitGraph = new GitGraph({
  template: metroWithBranchLabels,
  orientation: "horizontal",
  mode: "compact"
});
```

That would produce graphs like this:

<img width="1133" alt="capture d ecran 2017-01-25 a 08 05 05" src="https://cloud.githubusercontent.com/assets/1094774/22281062/0d1b13c4-e2d5-11e6-95dd-b24d88b52584.png">

Does it meet your needs?

---

Concerning your other suggestions (multiple labels on same commit, HEAD label, etc.), I does make sense to create individual issues for these from my point of view. This is not incompatible with the current path of the project, so feel free to create them 👍

**Comment by JKrag** [comment]
@nicoespeon Thanks for your reply. I had been playing around mostly with the vertical view. While I do admit that the labels look much better here in the horizontal it, unfortunately, does not meet my needs.
For me, it is a very important property of a branch label that it actually references (points to) a specific commit. As I see it, the labels in your example (and in my experiments) are always placed at the "beginning" of a branch, and I have no control over this or option to move them elsewhere.

In my experiments in the linked fiddle I at least managed to get them to move along with the last commit on the branch, but I wouldn't be able to demonstrate e.g. a checkout or reset HEAD~1.

I am afraid that supporting this would need some refactoring and be closely tied to the other feature I am suggesting about multiple branch labels on the same commit.

**Comment by nicoespeon** [comment]
> For me, it is a very important property of a branch label that it actually references (points to) a specific commit. As I see it, the labels in your example (and in my experiments) are always placed at the "beginning" of a branch, and I have no control over this or option to move them elsewhere.

Yep. Unfortunately, that's an issue of wrong design in the heart of the current version of gitgraph.js.

Branches should be tags that reference a commit, so we can retrieve it (and its ancestors). Graph content should just be a collection of commits that are related each others − a graph, basically.
But for now, gitgraph.js is made of branches that contains a list of commits. Branches are "physical" things that hold a list of unrelated commits.

It worked as a POC, but it has limit to mimic reality.

> In my experiments in the linked fiddle I at least managed to get them to move along with the last commit on the branch, but I wouldn't be able to demonstrate e.g. a checkout or reset HEAD~1.

Sure we might hack around the rendering part so branch label may be rendered next to the last commit of the branch rather than the beginning of it. It would solve most common use cases, but it will still not tackle the root cause.

> I am afraid that supporting this would need some refactoring and be closely tied to the other feature I am suggesting about multiple branch labels on the same commit.

I think the same. These are related.
And that's why we need to address the modelisation issue.

Fortunately, I started to play around this idea recently as I wish to make #38 come true. This is a great excuse to refactor the lib, extracting the rendering part from the API.
Doing so, I'm reconsidering the modelisation − and also setting up automated tests, but that's another point.

So my point is: good news, that's where the project is moving to.
The bad news is that it may take me some time to have something as complete as the current version. I may ship something when it will be good enough to address concerns the current version doesn't. But that will probably be a major version upgrade, with breaking changes.

I'll let you know about it.
