### ISSUE TITLE
Cannot render merging back

### ISSUE THREAD

**Issue by Ippo343** [nicoespeon/gitgraph.js#175]
I found that this graph does not render correctly.
I have a feature branch `A` that gets merged into `develop`. Then I would like to merge `develop` back into `B` and finally `B` into `develop`, but the last two merges are not rendered.

This is the rendered image (using JS Fiddle):
![download](https://user-images.githubusercontent.com/7579988/29768511-d41cca3e-8be6-11e7-927b-605054242daf.png)

I would expect to see `develop` (in grey) being merged into `B` (in yellow), and then a second merge back into `develop`.
Instead, the merge from `develop` to `B` is not shown.

This is the code (maybe it's wrong?):

     var gitgraph = new GitGraph({
       template: "metro", // or blackarrow
       orientation: "vertical",
       author: "John Doe",
       mode: "extended" // or compact if you don't want the messages
     });

     var develop = gitgraph.branch("develop");
     develop.commit();

     var A = develop.branch("A");
     var B = develop.branch("B");
     A.commit("Commit A");
     B.commit("Commit B");

     A.merge(develop);

     // These two merges are not rendered
     develop.merge(B);
     B.merge(develop);

**Comment by nicoespeon** [comment]
After (late) investigations, it turns out this fails on v1.6.0 and was finally fixed with [v1.8.1](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.8.1). 

Here's a playground showing this works on last release (v1.13.0): https://codepen.io/nicoespeon/pen/aapdXq?editors=0010 

Closing the issue, thank you for reporting 👋
