### ISSUE TITLE
Branch.showLabel, Branch.labelColor, Branch.labelFont are not documented.

### ISSUE THREAD

**Issue by damianb** [nicoespeon/gitgraph.js#178]
As on tin - at least three properties do not currently exist in the JSDoc documentation, which hinders their discovery.

ED: Also labelRotation?

**Comment by nicoespeon** [comment]
I realized no answer was given to this issue.

So, for the record, hopefully this will be addressed with v2 (#187). Thus, we're not working on this on v1.

However, if you wish to make a PR to bring that to v1, we'll happily review & release it 👌

**Comment by nicoespeon** [comment]
So, this is technically _not_ resolved for the `gitgraph.js` package… But we released `@gitgraph/react` in v1.0.0-0 and this issue was fixed here—it's a TS project, so everything is documented through types.

Thus, I'm closing this issue as we won't maintain the `gitgraph.js` package. There will be a `@gitgraph/js` package soon to replace it. 

We still accept PRs if someone really needs it, but I'd suggest moving to the aforementioned packages. Thanks 🙏
