### ISSUE TITLE
The  blackarrow template displays incorrect arrow

### ISSUE THREAD

**Issue by majvan** [nicoespeon/gitgraph.js#186]
Hi,
the following code shows that if after branching new branch you create first commit on parent branch, then the next commit on a new branch, the arrow does not show properly.

var gitgraph = new GitGraph({
  template: "blackarrow",
  reverseArrow: false,
  orientation: "horizontal",
  mode: "extended"
});
var master = gitgraph.branch("master");
master.commit()
var release1 = master.branch("release1");    // New branch from HEAD
master.commit();
release1.commit();
master.commit();

**Comment by nicoespeon** [comment]
This will be fixed with #187 👍

**Comment by twentytwokhz** [comment]
Joi, 30 aug. 2018, 14:54 Nicolas Carlo <notifications@github.com> a scris:

**Comment by nicoespeon** [comment]
So, this is technically _not_ resolved for the `gitgraph.js` package… But we released `@gitgraph/react` in v1.0.0-0 and this issue was fixed here.

Thus, I'm closing this issue as we won't maintain the `gitgraph.js` package. There will be a `@gitgraph/js` package soon to replace it. 

We still accept PRs if someone really needs it, but I'd suggest moving to the aforementioned packages. Thanks 🙏
