### ISSUE TITLE
Slow for large graphs

### ISSUE THREAD

**Issue by dimaqq** [nicoespeon/gitgraph.js#227]
I'm trying to get gitgraph-react to plot a large data set, extract from some repo with git2json:
* 7K commits
* M3 total lines of pretty JSON

The browser page seems to hang... for a very long time.

- OS: macOS
- Browser: Chrome stable
- gitgraph-core@2.0.0-alpha.73bd2e56
- gitgraph-react@2.0.0-alpha.73bd2e56

**Comment by nicoespeon** [comment]
Hi @dimaqq 👋 

Indeed, I'm not surprised this is happening. `import()` is still quite experimental, and we didn't test it for performance yet. 

I think I'll update the code so it fallback gracefully and explain the user about that, instead of just hanging… 

I'll keep your issue open until we improve perfs of `import()` 👍

**Comment by nicoespeon** [comment]
Hey @dimaqq!

We've bring some perf improvements in the latest release. We are able to render 1,261 commits in ~2s.

Could you try again with the latest release and tell me if it's acceptable to solve the overall issue? 
Note that you'd need to install `@gitgraph/react` package instead of `gitgraph-react`.

Thanks 👍

**Comment by nicoespeon** [comment]
Closing this issue. 

If anyone has perfs issues with large graph, don't hesitate to open a new one with details about your specific case so we can investigate and improve.
