### ISSUE TITLE
Render graph asynchronously

### ISSUE THREAD

**Issue by JackWilliam277** [nicoespeon/gitgraph.js#260]
Hi,

I'm sorry if it's a useless question.
But I'm asking how to render the graph asynchronously?

I'm using gitgraph.js and when I'm rendering a big repository graph it's freezing during few seconds and I can't interact with my app.

If someone has the soluce, thanks a lot!

**Comment by nicoespeon** [comment]
Hi @JackWilliam277 👋 

Rendering libraries don't render graph asynchronously for now. I think you would need to build up something yourself, putting the expensive calculation in a web worker so it doesn't impact the main thread. That might be a good lead.

However, you shouldn't have to do it. The problem is that `import()` is still a bit experimental, and we didn't work on it's performance yet. 

But I've good news for you:
- thanks to @haizz (#253), the `import()` function is now significantly faster
- I'll debounce the listener so rendering should also be significantly faster for large graph.

I didn't make a release yet, but these improvements will be available by the end of the week. Until then, if you really need them, you can point on `master`.

I hope that helps. Let me know if you have another question 👍
