### ISSUE TITLE
Plus add documentation for npm @gitgraph/js migration guide (link broken)

### ISSUE THREAD

**Issue by SumNeuron** [nicoespeon/gitgraph.js#266]
Please add documentation. The gitgraph.js website and the docs on @gitgraph/js do not overlap

**Comment by nicoespeon** [comment]
Thanks @SumNeuron for spotting the broken link! 
Indeed, it was relative so it wouldn't work on npm 🤦‍♂️ 

I fixed that on `master`. I'll publish a new release this evening with this fix, so it gets fixed on npm.

As for the website not being up-to-date, this is in progress indeed. It should be fixed in the following days. See #36 👍 

I'm closing the issue as it will be solved with #36.
