### ISSUE TITLE
Generate and publish API documentation

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/gitgraph.js#274]
The website have been revamped with #272.

We now have generic presentation of the library as well as use-case examples with Storybook.

Though, as an end-user, I'd like to have an official reference of the library API so I know everything that is possible. An end-user using TypeScript (or even JS IntelliSense) would have auto-completion. But I'd still like to generate the documentation from these types and put it online. 

It should be published with the website, just like the stories.

**Comment by nicoespeon** [comment]
We could use https://www.gitbook.com/ for this, this would simplify the doc on the presentational website

The idea is to document Gitgraph usage exhaustively, like https://jestjs.io/docs/en/api

**Comment by rwenz3l** [comment]
GitHub has wikis. I'd propose using that.

I am too missing the API specification since I'm only using this library occasionally and feel like I have to re-learn it every time from scratch. I'm using it on a simple HTML page or fiddle to create a graph, take a picture of it and put it in some documentation. An example question that I had: how do I set the template. Last time I used the Library it was `new GitGraph.Template()` now it's different?

Sure the name changed but for the love of god I just can't figure out how to properly use it in the simple js context.

Looked at the source code : good there is a template class, let's use that (`t = new GitgraphJS.Template();` Nope. Doesn't work.

Looked at the Storybook : Hmm.. looks like I have to install yarn/npm and some storybook package to make this work: Nope. Seems like it's not intended to be used by end-users. Great.. try to decipher what's in the storybook.. Hm, it just shows simple TemplateExtend examples, not a new template.

So yeah..

Please add proper documentation. The closest I have found is the migration guide from v1 to v2..

> like https://jestjs.io/docs/en/api

that seems overkill. How huge is gitgraph really? Does that make sense? 
Have a look at the d3.js wiki page: https://github.com/d3/d3/wiki

It's directly in the repo (very close together) and has lots of examples and the API specification how I'd expect it.

**Comment by nicoespeon** [comment]
Thanks for your feedback.

I didn't thought about GitHub wiki, that's indeed a good one to keep it simple and close to the source code 👍 

---

N.B. for v2, I've put up an online playground using the latest version automatically on CodePen: https://codepen.io/nicoespeon/pen/arqPWb?editors=1010

So you don't need the whole npm/TS stuff. It's in the [@gitgraph/js README](https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js) but yeah, I'd like to make it super-clear for everyone.

I'll take a final stab at this documentation / website issue when I got some free time.
