### ISSUE TITLE
@gitgraph/node is broken 

### ISSUE THREAD

**Issue by parmentelat** [nicoespeon/gitgraph.js#291]
**Describe the bug**

Following the instructions of the readme for using the node version, I get a syntax error

**To Reproduce**

1.  on a macos, 

```
$ uname -r
18.5.0
$ node --version
v12.1.0
$ npm -version
6.9.0

```
2. install as per the readme

```
$ npm i --save @gitgraph/node
$ cat > index.js
const { Gitgraph, render } = require("@gitgraph/node");

const gitgraph = new Gitgraph();

// Simulate git commands with Gitgraph API.
const master = gitgraph.branch("master");
master.commit("Set up the project");
....
EOF
```

3. run node

    $ node index.js

4.  See error

```
import { GitgraphCore } from "@gitgraph/core";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/tparment/git/flotpython-gittutorial/notebooks/index.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)

```

**Expected behavior**

some textual representation of a git repo

**Screenshots**

**Desktop (please complete the following information):**

see above

**Additional context**

I'm really not too familiar yet with the node/npm suite, but this feels like something is badly wrong with my expectations;

**Comment by nicoespeon** [comment]
Hi @parmentelat 👋 

Thanks for reporting. To be honest, the `@gitgraph/node` package is still under development. As we focused on the other packages, I didn't touched it for months, so the build may be broken for the moment.

I'll have a look and fix the build if needed. But for the moment, I'd recommend not using this one—it misses a bunch of features, so it won't render graphs properly yet.

**Comment by nicoespeon** [comment]
Yeah, I just tested: `@gitgraph/node` is broken. It didn't follow the redesign we did on the core library.

**Comment by parmentelat** [comment]
all right, thanks for letting me know, I'll pass then :)

**Comment by Symbolk** [comment]
@nicoespeon What a pity~Looking forward to use it, I want to use it in an electron app with vue, I am wondering if that can be done with the `@gitgraph/js`?

**Comment by nicoespeon** [comment]
@Symbolk hmmmm probably. If you have a web view (which I guess is the case since you're using Vue) then you can use the JS library. There is no Vue.js rendering lib for the moment, so you'd need to wrap the JS library into a Vue component I think—but I don't know Vue very much, so I can't tell 😅 

We've run into a quite similar need to build our stories with the JS lib. They needed to be exposed as React component in the end:

https://github.com/nicoespeon/gitgraph.js/blob/4f85de4702881326520a1efcd11a221835eb9031/packages/stories/src/gitgraph-js/1-basic-usage.stories.tsx#L13-L26

So we created a React component that exposes the vanilla JS lib: https://github.com/nicoespeon/gitgraph.js/blob/4f85de4702881326520a1efcd11a221835eb9031/packages/stories/src/helpers.tsx#L20-L39

I think you could do the same with Vue.

Let me know if you succeed or if you need help 👍

**Comment by nicoespeon** [comment]
The node version was mostly a POC that any rendering lib would work. But it would've rendered the graph in a terminal, so I'm not sure it would have fit your needs for an Electron app anyway 🤔
