### ISSUE TITLE
Cannot set both author and message for commit

### ISSUE THREAD

**Issue by profgiuseppe** [nicoespeon/gitgraph.js#301]
**Describe the bug**

While using the commit function, either the message is ignored or the author is.

**To Reproduce**

Reproduce the issue [with the online playgound](https://codepen.io/anon/pen/mZOrrz?editors=0010).

**Expected behavior**

Both the message and the author are changed according to the arguments.

**Context**

- Which library is impacted? `@gitgraph/js`
- Which version of the library is it? https://cdn.jsdelivr.net/npm/@gitgraph/js
- What browser and version is impacted? Firefox 60.7.0esr, Chromium Version 73.0.3683.75

**Comment by nicoespeon** [comment]
Hi @profgiuseppe 👋 

Thanks for reporting. Actually, the problem is that `message` is not a valid property for commit options. It's splitted between `subject` and `body` (which, together, define the commit "message"). See the signature:

https://github.com/nicoespeon/gitgraph.js/blob/4f85de4702881326520a1efcd11a221835eb9031/packages/gitgraph-core/src/user-api/gitgraph-user-api.ts#L22-L23

Thus, this should work as you expect:

```js
master.commit({subject: "Initial commit", author: "Giuseppe <giuseppe>"});
```

It makes me think that maybe having a `message` attribute would be more intuitive. Instead of having `subject` and `body`, we'd have a `message` that would either be a `string` (shorthand for subject), or an object `{ subject, body }`.

I'll create another issue to track that 👍

**Comment by profgiuseppe** [comment]
Thanks. The misleading piece of information was this old blogpost https://www.nicoespeon.com/en/2013/11/gitgraphjs/
