### ISSUE TITLE
Make Graph Scale Responsive

### ISSUE THREAD

**Issue by aensley** [nicoespeon/gitgraph.js#303]
_Disclaimer: I am an SVG newbie_

**Is your feature request related to a problem? Please describe.**
The SVG element rendered by this library in browser is set to a specific width and height. This does not work well if a user is on a smaller screen or when the graph needs to be contained in a smaller element in the layout.

See point 2 on this page: https://www.creativebloq.com/how-to/10-golden-rules-for-responsive-svgs

**Describe the solution you'd like**
I would like the SVG to scale automatically within its parent.

**Describe alternatives you've considered**
I've attempted to alter the SVG and its parents using multiple responsive SVG techniques. None have worked for me.

**Additional context**
I attempted as many of the techniques in these articles as could be applied to the inline SVG:
* https://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/
* https://css-tricks.com/scale-svg/

**Comment by zeqk** [comment]
there is any temporal approach?

**Comment by longgt** [comment]
I take a look at http://thenewcode.com/744/Make-SVG-Responsive
then made some changes, everything works like a charm.

1. Remove **width** and **height** attribute
Add `preserveAspectRatio="xMinYMin meet"` and `viewBox="0 0 width height"` instead.
2. Create a container of svg with the following style

```
.svg-container { 
	display: inline-block;
	position: relative;
	width: 100%;
	padding-bottom: 100%; 
	vertical-align: middle; 
	overflow: hidden; 
}
```

3. Adjust svg style

```
.svg-content { 
	display: inline-block;
	position: absolute;
	top: 0;
	left: 0;
}
```

**Comment by aensley** [comment]
_Replying to https://github.com/nicoespeon/gitgraph.js/issues/303#issuecomment-592453362 by @longgt:_

Yes, this is essentially what I'm asking @nicoespeon to do. It has to be a change in gitgraph.js itself.

@longgt, Since you've already figured out the fix, perhaps you could submit a pull request?

**Comment by marekyggdrasil** [comment]
@aensley thanks for identifying the problem and @longgt thanks for helping diagnosing it!

I'm not really a js expert, I also joined in the project because there is a feature I need, I know the source more or less and I think styles are defined here https://github.com/nicoespeon/gitgraph.js/blob/c630d2006dd6e975708a2ba3999a6ca95dce244d/packages/gitgraph-core/src/template.ts#L404-L446

To my understanding there is no style defined for entire container (but I might be wrong), I think we would need @nicoespeon to comment on that.

If it is not defined, it seems absolutely necessary we would need to include it to handle the responsivity of the entire graph container.

**Comment by longgt** [comment]
@marekyggdrasil the width and height of graph container is defined here.

https://github.com/nicoespeon/gitgraph.js/blob/c630d2006dd6e975708a2ba3999a6ca95dce244d/packages/gitgraph-js/src/gitgraph.ts#L247

**Comment by nicoespeon** [comment]
If the change is made in `@gitgraph/js` library, then I think the best is to extend the options of the lib to provide what you need: https://github.com/nicoespeon/gitgraph.js/blob/c630d2006dd6e975708a2ba3999a6ca95dce244d/packages/gitgraph-js/src/gitgraph.ts#L63

You can define `GitgraphOptions & { something: "else" }` and make it work for this lib.

If the problem needs to be fixed in the other libs, then we could pull up the options. But starting here is fine IMO.

**Comment by liesislukas** [comment]
could anyone familiar with this lib just push this? seems like tiny change for someone with experience with this repo

**Comment by nicoespeon** [comment]
I'll try to have a look this week-end. I can't promise anything because I won't have much time to dedicate, but if I can get you unblocked with a little change I'll make it so 👍

**Comment by nicoespeon** [comment]
@all-contributors please add aensley for ideas

@all-contributors please add longgt for ideas

**Comment by nicoespeon** [comment]
@all-contributors please add aensley for ideas

**Comment by nicoespeon** [comment]
@all-contributors please add longgt for ideas

**Comment by nicoespeon** [comment]
I just did a new release of all packages, this is available now =)

You can use the new `responsive` boolean option with `@gitgraph/js`. Setting it to `true` will make the graph fill the available space of its container:

```js
const gitgraph = createGitgraph(graphContainer, {
  generateCommitHash: createFixedHashGenerator(),
  responsive: true,
});
```

![responsive-gitgraph](https://user-images.githubusercontent.com/1094774/110209002-28b36780-7e58-11eb-9b80-83b1138cde96.gif)

**Comment by mikevd92** [comment]
The option does not work in gitgraph react 1.6.0
