### ISSUE TITLE
dot colors don't follow branch color

### ISSUE THREAD

**Issue by Hoshani** [nicoespeon/gitgraph.js#316]
I am trying to make dots follow the color of the branch, but I am unable to do it

sample code modified here
https://codepen.io/anon/pen/OKbqZe

is there any a way to change the colors of the text and the dot? (even if it is a temporary solution)

**Comment by nicoespeon** [comment]
@Hoshani thanks for creating a codepen to illustrate the issue.

In fact, if we want to customize commit style of a branch, we need to use the `commitDefaultOptions` attributes in the branch options. So that would be:

```js
const master = gitgraph.branch({
  name: "master",
  style: {
    color: "#6963FF"
  },
  commitDefaultOptions: {
    style: {
      message: {
        color: "#6963FF"
      },
      dot: {
        color: "#6963FF"
      }
    }
  }
});
```

You can see what's available here: https://github.com/nicoespeon/gitgraph.js/blob/2702d9275e5bd97cfe1230810ba20f380a811402/packages/gitgraph-core/src/user-api/gitgraph-user-api.ts#L41-L58

However, if what you want is define a new set of colors for the whole graph and get that applied to branches, commits and tags, I think the best solution is to define your own template. Here's an example:

```js
const gitgraph = GitgraphJS.createGitgraph(graphContainer, {
  template: GitgraphJS.templateExtend("metro", {
    colors: ["#6963FF", "#008fb5", "#f1c109"]
  })
});
```

This way, you don't need to redeclare the colors for every branch.

Default templates are defined here:
https://github.com/nicoespeon/gitgraph.js/blob/2702d9275e5bd97cfe1230810ba20f380a811402/packages/gitgraph-core/src/template.ts#L348-L371
https://github.com/nicoespeon/gitgraph.js/blob/2702d9275e5bd97cfe1230810ba20f380a811402/packages/gitgraph-core/src/template.ts#L376-L391

And here are the possible template attributes you can configure: https://github.com/nicoespeon/gitgraph.js/blob/2702d9275e5bd97cfe1230810ba20f380a811402/packages/gitgraph-core/src/template.ts#L218-L239

Is that satisfying your needs? Do you have further questions?

**Comment by nicoespeon** [comment]
Also, intuitively I agree that setting the color of the branch should automatically adapt the color of the commits.

This bug has been documented here already: https://github.com/nicoespeon/gitgraph.js/issues/244

We started working on a fix, but I didn't have time to move on that recently. 

Thus, I'm closing the issue. But don't hesitate to re-open it (or a new one) if you have any further question or suggestion 👍 
Thank you!

**Comment by Hoshani** [comment]
amazing, thanks for your helpful detailed answer

**Comment by sc250024** [comment]
Sorry to comment on closed issue. I'm now just using something like what's above...

```javascript
const master = gitgraph.branch({
  name: "master",
  style: {
    color: "#6963FF"
  },
  commitDefaultOptions: {
    style: {
      message: {
        color: "#6963FF"
      },
      dot: {
        color: "#6963FF"
      }
    }
  }
});
```

...on every new branch. However the branch name, branch name outline, and tag background color all don't match. Using the method above, how do I make sure _everything_ for a branch (branch line, commit message, branch name, branch name outline, and tag background) are all the same color? In other words, what else is missing from the above config to achieve that?

**Comment by sc250024** [comment]
Nevermind, read the docs. Here's the code to create consistent coloring across the entire branch:

```javascript
    const someBranch = gitgraph.branch({
      name: "some-branch",
      style: {
        color: "#00b894",
        label: {
          strokeColor: "#00b894"
        }
      },
      commitDefaultOptions: {
        style: {
          color: "#00b894",
          message: {
            color: "#00b894"
          },
          dot: {
            color: "#00b894"
          }
        }
      }
    });
```
