### ISSUE TITLE
Branch name overlaps with drawing in horizontal mode

### ISSUE THREAD

**Issue by Hoshani** [nicoespeon/gitgraph.js#319]
**Describe the bug**

Branch names get in the middle of the arrows

**To Reproduce**

[online playgound](https://codepen.io/anon/pen/OKbqZe).

**Expected behavior**

names should not overlap

**Question**
is there a way to change the location of the branch name? I am trying to do something like [git flow explaining image](https://datasift.github.io/gitflow/GitFlowFeatureBranches.png) but horizontally

**Comment by nicoespeon** [comment]
Hi @Hoshani 👋 

Yes, this is related to the comment I made about rendering tags in horizontal mode: https://github.com/nicoespeon/gitgraph.js/issues/237#issuecomment-475102442

> is there a way to change the location of the branch name?

In fact, yes. You can provide a `renderLabel()` that takes the `branch` and should return an SVG element for the JS package, or a React element for the React package.

Imagine the following implementation:

```js
function renderLabel (branch) {
  // These colors come from the template definition
  // https://github.com/nicoespeon/gitgraph.js/blob/28e39442eca0daa10bfb99141f6616fc66b6d217/packages/gitgraph-core/src/template.ts#L349
  const colors = ["#6963FF", "#47E8D4", "#6BDB52", "#E84BA5", "#FFA657"];
  const branches = Array.from(branch.gitgraph.branches.keys());
  const branchIndex = branches.findIndex(name => name === branch.name);
  const offset = branch.style.spacing * (branches.length - branchIndex);
  
  return createText({
    content: branch.name,
    fill: colors[branchIndex % colors.length],
    font: "16px Helvetica",
    translate: { 
      x: -70,
      y: offset,
    },
    rotate: -20
  })
}

// 👇These helpers I copied from 
// https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/src/svg-elements.ts
const SVG_NAMESPACE = "http://www.w3.org/2000/svg";
function createText(options) {
  const text = document.createElementNS(SVG_NAMESPACE, "text");
  text.setAttribute("alignment-baseline", "central");
  text.setAttribute("dominant-baseline", "central");
  text.textContent = options.content;

  if (options.fill) {
    text.setAttribute("fill", options.fill);
  }

  if (options.font) {
    text.setAttribute("style", `font: ${options.font}`);
  }

  if (options.anchor) {
    text.setAttribute("text-anchor", options.anchor);
  }

  if (options.translate) {
    text.setAttribute("x", options.translate.x.toString());
    text.setAttribute("y", options.translate.y.toString());
  }

  if (options.rotate) {
    text.setAttribute("transform", `rotate(${options.rotate})`);
  }

  if (options.onClick) {
    text.addEventListener("click", options.onClick);
  }

  return text;
}
```

Now in the code, if we use `develop.branch({ name:"a-feature", renderLabel })` instead of `develop.branch("a-feature")` for every branch we create, we'll have the following result:

![image](https://user-images.githubusercontent.com/1094774/62423479-a7e62580-b68e-11e9-8379-9f83573d1760.png)

It's not ideal, but it works. You can even go further on how you draw the branch label so you have a rectangle around the text. You can use [the SVG helpers we created](https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/src/svg-elements.ts) and have a look to [how the default branch labels are rendered](https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/src/branch-label.ts) (note however that you don't have access to the `commit` in the custom method).

**Comment by Hoshani** [comment]
unfortunately I had to resort to something specifically written to achieve desired result 

but here is what I wanted to create, this might give you an idea of a new style

![image](https://i.imgur.com/ne9EyNG.png)
