### ISSUE TITLE
Black arrow was rendered incorrectly when created branch from another branch

### ISSUE THREAD

**Issue by longgt** [nicoespeon/gitgraph.js#354]
**Describe the bug**

1. Commit 2 revision to **master**
2. Create **develop** branch from **master**
3. Commit 1 revision to **master**
4. Branch **feature/issXXX** from **develop**
5. Commit to **feature/issXXX**
6. Branch **hotfix/issYYY** from **master**
7. Commit to **hotfix/issYYY**
8. Merge **feature/issXXX** to **develop**
→Black arrow was not rendered, just path.

If I didn't branch **hotfix/issYYY** from **master**, everything was render correctly.

**To Reproduce**

https://codepen.io/longgt/pen/JjYENpP

**Expected behavior**

Black arrow was rendered correctly when merging branch.

**Screenshots**

![branch_merge](https://user-images.githubusercontent.com/27258608/80058827-872f6a00-8554-11ea-9e86-369950f641e9.PNG)

**Comment by edwardwall** [comment]
A more minimal reproducible case  

```
const gitgraph = GitgraphJS.createGitgraph(graphContainer,
    {template: 'blackarrow', orientation: "horizontal"});

const master = gitgraph.branch("master");
master.commit();

const develop = master.branch("develop");
develop.commit();

master.commit();

master.merge(develop);
```

![image](https://user-images.githubusercontent.com/56203203/84084019-95d5c180-a9da-11ea-85e9-19b007964314.png)

**Comment by S1ngS1ng** [comment]
@nicoespeon I did a little bit of research on this issue. Sorry that I am not able to provide a PR for this. But here is what I've found so far, based on the example provided (https://codepen.io/longgt/pen/JjYENpP):
1. Given `vertical` instead of `vertical-reverse`, the arrow is still missing on the other side
![image](https://user-images.githubusercontent.com/13592559/86561556-c6474780-bf15-11ea-830d-dc4eb27b711c.png)
2. By inspecting the element, I noticed that there are actually two arrows rendered, for both `vertical` and `vertical-reverse`. Though, it looks like the two arrows are stacked:
![image](https://user-images.githubusercontent.com/13592559/86561753-348c0a00-bf16-11ea-8a6b-376d6af09763.png)
(I manually changed the `translate` for one):
![image](https://user-images.githubusercontent.com/13592559/86561865-74eb8800-bf16-11ea-82db-094ff1e90418.png)
3. Commit with message of "Make it fast" on `a-feature` branch does have the correct parent, which is the one with message of "Merge branch a-feature". So IMHO, [this code](https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/src/gitgraph.ts#L321) should be doing fine
4. Then, when it comes to drawing SVG path, I barely have knowledge regarding that part :( Just guessing around, the problem might be [here when calculating origin](https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/src/gitgraph.ts#L325) or [here when calculating arrow path](https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-core/src/utils.ts#L115). IMHO it could be the latter one since the arrow path is not done correctly anyway (should have been rotated clockwise a little bit)

Unfortunately, this is what I could do so far for this issue. Please let me know if you need more info, or if you may let me know some resources regarding the SVG path topic, that would be perfect. Thanks in advance

**Comment by nicoespeon** [comment]
Thanks @S1ngS1ng 👍 

I won't have time to dig into this personally but that surely will be helpful.
The arrow path calculation seems to be the culprit indeed.
