### ISSUE TITLE
Show selected commit/merge and return selected item hash

### ISSUE THREAD

**Issue by andreaboriani** [nicoespeon/gitgraph.js#356]
Is there a way to mark a commit as selected (programmatically and when clicking) and retrieve the selected node hash?

**Comment by fabien0102** [comment]
https://codesandbox.io/s/quizzical-chebyshev-pceyj?file=/src/App.tsx (you can click on the commit dots)

I played a bit, this is the best I have for now regarding the current API, since we don't really have a way to tell to Gitgraph that something happens, I use the "key hack", but works.

Render props is definitely not the best pattern for this kind of usecase 😬
