### ISSUE TITLE
Git Branches Overlap

### ISSUE THREAD

**Issue by mrenvoize** [nicoespeon/gitgraph.js#40]
I'm not sure if this is a bug or a lack of understanding/documentation reading on my part.

I have an example graph available at: http://gitgraph.ptfs-europe.co.uk/koha/

From the example you can see that the initial branch crosses other branches, but by moving that first branch further down, you could display a clearer tree without the crossovers.

I'm basically trying to diagrammatically show a gitflow workflow, but this makes it look more complex than it is.

Could you point me in the right direction?

**Comment by xortim** [comment]
I'm also trying to implement a gitflow-like graph and ran into this same issue. It definitely adds complexity to the illustration. This is definitely one of those easy to explain but more difficult to implement features.

**Comment by nicoespeon** [comment]
Not sure this has been solved with the release of `@gitgraph/react`. We'd need to try complex scenarios and see how rendering is made.

The good news is that we can now easily write tests on the rendering part, meaning we can tweak and optimize rendering to generate less "complex" illustrations.

**Comment by nicoespeon** [comment]
Hey everyone 👋 
This is quite an old issue, but I've got some news since v2.

In `@gitgraph/js` and `@gitgraph/react`, you can now provide a `compareBranchesOrder()` function to sort branches in a more convenient order (default is historical order). There's a story illustrating usage: https://github.com/nicoespeon/gitgraph.js/blob/cda0b6db3892ea6588681b7ad0868f886390a18b/packages/stories/src/gitgraph-js/1-basic-usage.stories.tsx#L318-L343

I feel the feature fixes this issue, since you can re-order branches as you wish to generate a simpler graph.

Thus, I'm closing this issue. Feel free to re-open one if you found a use case that couldn't be fixed 👍
