### ISSUE TITLE
Fit inside wrapping container (or allow custom width)

### ISSUE THREAD

**Issue by dwelle** [nicoespeon/gitgraph.js#50]
mainly for horizontal graphs.

**Comment by nicoespeon** [comment]
Note for later: 6d0ddf456ff5dcc3df5b3e2f71a70ca6dfdf5a42 might be helpful

**Comment by nicoespeon** [comment]
So, this is technically _not_ resolved for the `gitgraph.js` package… But we released `@gitgraph/react` in v1.0.0-0 and this issue was fixed here. Graph container automatically adapts its dimension to fit what is rendered. You can put it into some scrollable box, if you wish to.

Thus, I'm closing this issue as we won't maintain the `gitgraph.js` package. There will be a `@gitgraph/js` package soon to replace it. 

We still accept PRs if someone really needs it, but I'd suggest moving to the aforementioned packages. Thanks 🙏
