### ISSUE TITLE
Adding support for 'fast-forward' merge

### ISSUE THREAD

**Issue by ckruczek** [nicoespeon/gitgraph.js#67]
Hey guys,

I am pretty stuned about your work, and really like to use the library moreover. One little feature  I was missing is the `fast-forward` merge. In this example http://jsfiddle.net/guan1oz1/101/ I would expect to get a clear liniear history because thats clearly a fast-forward. Did i missed a option or something?

**Comment by nicoespeon** [comment]
Hi @ckruczek,

Thanks a lot for your feedback. 
I'm not sure I can see where the fast-forward should appear in your gist since you committed in both branches before calling `.merge()`, but there still miss a `fast-forward` option anyway :smiley: 

I'll add this to the roadmap. Thanks for the use case :wink:

**Comment by ckruczek** [comment]
Thanks for your comment. I missed saving my gist before adding it to the issue. So I will update this and a new gist later. Thanks for your tip.

**Comment by ckruczek** [comment]
As I already told,here is the updated version of the [giddle, jiddle what ever...](http://jsfiddle.net/guan1oz1/101/) This could clearly result in a fast-forward because master did not diverged after develop was branched off. Thanks for adding it as feature! Really appreciate it.

Kind regards 

ckruczek

**Comment by nicoespeon** [comment]
Yup, thanks for the fiddle, that will be useful :+1:

**Comment by sofusalbertsen** [comment]
Hi @nicoespeon, first of thanks for a fantastic library!
I'm working on making some guides using this, but I need the fast-forward merge capability to illustrate that.
I can see that you have moved the milestone into infinity.
Is that because it is not possible to do it, or "just" a matter of priorities?
-Sofus

**Comment by nicoespeon** [comment]
Hi @sofusalbertsen!

Well, to sum it up: this project was a good-enough solution we developed with @fabien0102 to fill our needs to render git graphes in JS few years ago. Since, I mostly accepted pull-requests and fixed a few bugs, but I went to other projects so I did not really move the library forward.

I feel like the code still has some bugs but no tests and all-in-one big chunk that doesn't help to introduce new features easily & with confidence.

The good news is that I don't have another currently running side-project and I am willing to come back to this project and make it better, solving bugs and adding missing features like this one − motivation is everything.

Let me give a fresh new look at it this week and I will update issues with a new planning 👌

**Comment by sofusalbertsen** [comment]
Hi again @nicoespeon.
If you have time, then that would be amazing, I really like working with your library :)
-S

**Comment by nicoespeon** [comment]
Hi again @sofusalbertsen!

Get some time to have a look to the project and clean the dust a bit.

There are few points to improve with the project:

- do more tests − actually, [there are some](https://github.com/nicoespeon/gitgraph.js/blob/develop/tests/gitgraph.js) I forgot about
- modularize source code in some way, so it would be more manageable
- have a look at tooling & dependencies we use, to get up-to-date

But I feel all of this can be done along the way. I don't want to spent some time just "tweaking the tooling" as it won't add any actual value to the library.

About planification: I don't want to over-plan things neither, so I'm not creating new "planned milestones" for now.

I'll just take this issue and see want I can do in the following days on my spare time. Then I'll take another and so on… I will make the lib more manageable along the way of solving issues: that's my plan for now.

I'll get you updated with my progression on this issue.
Thanks!

**Comment by sofusalbertsen** [comment]
@nicoespeon That sounds fantastic :)
I totally agree that your time is better spent on making improvements, than tight planning, especially when this is spare time development.

Again, thank you for "reviving" this, I really see the benefits of having an open-source git-graph drawing lib such as this!
-S

**Comment by nicoespeon** [comment]
Hi @ckruczek & @sofusalbertsen!

With the [latest release](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.6.0) you can now do something like `featureBranch.merge(mainBranch, { fastForward: true });` to perform a fast-forward merge if possible. If it's not possible, it will do a regular merge.

Let me know if that works as you'd expected or if you have any trouble with that.
