### ISSUE TITLE
Non-functional on iOS

### ISSUE THREAD

**Issue by sourtin** [nicoespeon/gitgraph.js#73]
Gitgraph doesn't seem to work at all in Safari on iOS 8.3. I don't have an android phone to check, so maybe it works there. Interestingly I can't seem to find any errors or warnings relating to the canvas, and the detail boxes are moved to their correct positions and displayed, so the script seems to be running properly but the canvas is blank.

**Comment by nicoespeon** [comment]
Hi @sourtin!

I'm afraid this sounds familiar to me. In fact, this probably due to the OS + browser which makes canvas kept blank if you go over 4096px, something like that.

We ran into this kind of issue here: https://github.com/nicoespeon/gitgraph.js/issues/32

Is it the same issue you're running into?

**Comment by sourtin** [comment]
Hi @nicoespeon,
You're right, it's the same issue -- I just tried changing the scalingFactor down to 0.2 and it displayed! Hopefully the fix will reach iOS soon. Thanks for the quick reply!

**Comment by sourtin** [comment]
This is fixed in iOS 8.4

**Comment by riconeitzel** [comment]
It's not fixed in iOS 9.3.2
