### ISSUE TITLE
event attributes readonly error

### ISSUE THREAD

**Issue by ekocode** [nicoespeon/gitgraph.js#80]
hello,
great job for gitgraph :) thx...

I found a bug with the event.offsetX. event attributes are read only (on chrome)
I fix the error like that :

I changed event.offsetX for event_offsetX

    // Fix firefox MouseEvent
    var event_offsetX = event.offsetX ? event.offsetX : event.layerX;
    var event_offsetY = event.offsetY ? event.offsetY : event.layerY;
    var event_x = event.x ? event.x : event.clientX;
    var event_y = event.y ? event.y : event.clientY;

see ya
eko

**Comment by sielay** [comment]
+1

**Comment by nicoespeon** [comment]
Thanks for reporting, will have a look ;-)

**Comment by nicoespeon** [comment]
@ekocode > as you reported having troubles with Chrome and this snippet of code, I wonder if that's still the case since we now ensure to target Firefox specificly: https://github.com/nicoespeon/gitgraph.js/blob/develop/src/gitgraph.js#L334-L340

Could you confirm the bug still exist then? Thank you so much :smiley:
